add ability to recieve and send Audio
btsdigital/pyAitu pull request #31
Opened 2019-10-17 10:12 UTC by temagi

2019-10-17 11:31 UTC, yerassyl94 requested changes

2019-10-17 11:31 UTC, yerassyl94 commented on examples/echo_bot.py
> +    await bot.send_media(message.chat.id, 'images/cat.jpg', "IMAGE")
please change string value "IMAGE" to typealias like here [https://github.com/btsdigital/pyAitu/blob/develop/pyAitu/models/form/input_type.py](url)

2019-10-17 11:31 UTC, yerassyl94 commented on pyAitu/bot/bot.py
> +                         file_type: str):
file_type wait here typealias instead of string

2019-10-17 12:15 UTC, temagi commented on examples/echo_bot.py
> +    await bot.send_media(message.chat.id, 'images/cat.jpg', "IMAGE")
fixed

2019-10-17 12:16 UTC, temagi commented on pyAitu/bot/bot.py
> +                         file_type: str):
fixed

2019-10-18 06:21 UTC, yerassyl94 approved these changes

2019-10-18 06:22 UTC, merged